### ISSUE TITLE
VR.mp4 file not playing

### ISSUE THREAD

**Issue by weberbry** [Aralekk/simple360player_iOS#1]
The current project compiles and runs on both the simulator and device but just displays a full grey screen. 

UIPanGestureRecognizer responds to gestures and I can see and play the VR.mp4 in xcode but still can't see the VP.mp4 video in the app.

**Comment by Aralekk** [comment]
Hello,  

Are you building on a device or on the simulator ?
Just downloaded the project from github and runned it on an iPhone 6S+ to check and everything seems ok.
It doesn't on play the video in the simulator though. I'd have to look into it as to make it run there too !

Can you check on a device and update me ?

Arthur

**Comment by weberbry** [comment]
Tried running again on the device and works great.

Thanks.

**Comment by teamtomsk** [comment]
Hi,

I'm having the same grey screen issue on the iPad Mini. Is iOS 9.2 the minimum deployment target? the iPM is currently on 9.1 as a test device. But not receiving any errors (obvious ones anyway).

Any thoughts would be greatly appreciated. As this looks really cool and efficient...

Thanks, Stewart.

**Comment by Aralekk** [comment]
Hello teamtomsk,

We made the project iOS 9.2 as the deployment target but I don't see why it would work if you changed it in the project settings.

Are you building on your device or Simulator ?

Best,
Arthur

**Comment by teamtomsk** [comment]
Hi there,

Thanks for getting back... Sorry it's taken me a while to respond...

It works fine on my iPhone 6s, but not on the iPad Mini (as yet) - yet to try it on the iPad Air 2.  

I've lots of updating of hardware to do before I can say for certain what it works on and what it doesn't.

I'll give it a good play and get back to you with any thoughts if you like. I'll also see if I can take it a little further as it's right up my street - if I manage anything interesting, I'll drop you a copy to play with. 

Cheers,

Stewart.

**Comment by Aralekk** [comment]
Great Thanks ! Will be much appreciated ! :)
