### ISSUE TITLE
How did you arrive at the value of 30 for the sphere radius?

### ISSUE THREAD

**Issue by alfiehanssen** [Aralekk/simple360player_iOS#13]
Just curious, I see people choosing seemingly random numbers for the sphere radius. How did you arrive at the value of 30?

**Comment by Aralekk** [comment]
It was pretty much trial and error.
Also having a "large" enough sphere allows to tweak a bit more its SegmentCount property as to optimize performance. 
https://developer.apple.com/library/mac/documentation/SceneKit/Reference/SCNSphere_Class/#//apple_ref/occ/instp/SCNSphere/segmentCount
