### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by cyxse** [Aralekk/simple360player_iOS#2]
Memory leak when playing by Xcode profile tool launch app, why?

**Comment by Aralekk** [comment]
Will have a look

**Comment by Rannie** [comment]
skscene and skvideonode not dealloc

**Comment by Aralekk** [comment]
Yes, I will put a fix, thank you !

**Comment by Aralekk** [comment]
Should be better now

**Comment by NickAtGit** [comment]
Nope still leaking. Have a look at this: https://forums.developer.apple.com/thread/21855
Play the video 2-3 times (scrub back). Received memory warning will appear 2-3 times in the debugger and then it crashes. I'm experiencing the same with my own version of a VR 360 video player. Please file a bug report at Apple. This has been unfixed for some time...

**Comment by Aralekk** [comment]
Not able to reproduce here, if it happens I'll file a radar, thanks NickAtGit

**Comment by kosso** [comment]
This is still happening for me. 
Try making the video loop. I also just had it happen on a longer YouTube 360 mp4 url. It crashed after a few minutes. 

To loop a video I added : 

```
        NSNotificationCenter.defaultCenter().addObserver(self,
            selector: "loopVideo",
            name: AVPlayerItemDidPlayToEndTimeNotification,
            object: player?.currentItem
        )
```

and 

```
    func loopVideo()  {

        player!.pause()

        let seconds : Int64 = 0
        let preferredTimeScale : Int32 = 1
        let seekTime : CMTime = CMTimeMake(seconds, preferredTimeScale)
        player!.seekToTime(seekTime)
        player!.play()
    }
```

Try letting it run for a few minutes or loops.

**Comment by Aralekk** [comment]
@kosso did just that and let it run 7-8 times without issue :/ I am on a 6S plus maybe that's that. I ll try on an iphone 5

**Comment by kosso** [comment]
@Aralekk I'm on an iPhone6 running iOS 9.2.1 

I just let it run with the included vr.mp4 demo and the memory warnings started after about 40 seconds, then crashed a few seconds later.

**Comment by NickAtGit** [comment]
The bug definitely is still present, run a memory leak profile with instruments...

**Comment by kosso** [comment]
Yes. Running through Instruments shows the memory heap growing and growing to over a 1Gb until it crashes. 

I thought it might be my looping. But playing a long 360 mp4 from YouTube caused the same result eventually.  I can't quite tell what's causing it. But there are a lot of references to something called "jet_texture_Metal" taking up the majority of the persistent allocations. This seems to have something to do with SpriteKit.

**Comment by micahchiang** [comment]
Wanted to bump this. Did anyone come to a solution for the memory leak? I've been trying and cannot find one.

**Comment by kosso** [comment]
Same here. No luck.

**Comment by sajoneri** [comment]
Bumping. iOS 9.3.2, the issue remains :(

**Comment by NickAtGit** [comment]
I am at WWDC in June. I will talk to the SceneKit team there and hope they'll fix it soon...

**Comment by sajoneri** [comment]
Awesome, I keep my fingers crossed :)

**Comment by Aralekk** [comment]
@NickAtGit I'll be at WWDC too, maybe we can catchup and go at them a unified front ? ;)
Hope the fix will come sonner rather than later..

**Comment by NickAtGit** [comment]
@Aralekk yeah let's do this

**Comment by sajoneri** [comment]
Unified front sounds like a winner. At the moment I had to turn to [Google VR SDK](http://cocoadocs.org/docsets/GVRSDK/0.8.0/index.html) but it just doesn't feel right ;)

**Comment by avantcontra** [comment]
@sajoneri It seems that Google VR SDK doesn't support stereo video?

**Comment by sajoneri** [comment]
They do, it’s called cardboard and has a toggle button implemented in GVRWidgetView (http://cocoadocs.org/docsets/GVRSDK/0.8.0/Classes/GVRWidgetView.html http://cocoadocs.org/docsets/GVRSDK/0.8.0/Classes/GVRWidgetView.html)

**Comment by avantcontra** [comment]
@sajoneri OK Thanks. 
I also found this: "Stereo videos should be 1:1 aspect ratio." https://developers.google.com/vr/concepts/vrview#supported_formats

**Comment by NickAtGit** [comment]
@Aralekk where are you at WWDC? I'm sitting in the Broadway download area in front of Pacific Heights... The SceneKit Lab is this afternoon

**Comment by Aralekk** [comment]
Ok I'm coming up ! You can reach me(415) 483 6088

**Comment by Aralekk** [comment]
Ok i asked everybody there, you must have left :) reach me on twitter @aswiniarski if you want to meet :)
