### ISSUE TITLE
Audio Playback

### ISSUE THREAD

**Issue by weberbry** [Aralekk/simple360player_iOS#3]
For mp4 files that have audio I can not get the audio to be included in the playback. The volume property for the underlying AVPlayer is 1.0 but there is still no audio.

Any suggestions?

**Comment by Aralekk** [comment]
Simulator or device ? 
I can't reproduce the issue, can you walk me through what you've done ?
Did you also turn off the mute switch on a iPhone ? Happens to me all the time ! :)

**Comment by weberbry** [comment]
Audio switch issue.

Sorry about the silly question.
