### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by micahchiang** [Aralekk/simple360player_iOS#7]
Hi Aralekk, 

I've discovered that with long videos, over 20 seconds, there is a major memory leak that causes the app to crash. I believe it is caused by the renderer function.

When reworking the view controller to non stereoscopic, using only left scene camera, there are no memory issues. 
I've tried debugging this, but have had no success. I was wondering if you would take a look at it possibly. 

Thank you, 

Micah

**Comment by Aralekk** [comment]
Yes, We've been looking into it and have not found a way to correct it yet.. I will commit some fixes when we have them .. Sorry it takes this long, Apple seems clueless about it too
